spring.application.name=kitchen-hub

spring.mvc.apiversion.use.path-segment=1

# spring.modulith.detection-strategy=explicitly-annotated

# make it to `explicitly-annotated` if you want spring-modulith to detect only packages that are annotated

spring.modulith.detection-strategy=direct-sub-packages